version: "3"

services:

  # report-nginx:
  #   image: nginx:alpine
  #   container_name: login_report_host
  #   ports:
  #     - "9090:90"
  #   volumes:
  #     - ./nginx/html:/usr/share/nginx/html
  #     - ./nginx-live.conf

  tradersboard_widgetloadtest:
    build: .
    container_name: tradersboard_widgetloadtest
    privileged: true
    restart: always       
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
       - DISPLAY=:99
       - ENVIRONMENT=production
       - EMAIL_USER=neksoftautomationdev@gmail.com
       - EMAIL_PASS=rxkqlgmswevrdzpi
       - BASE_URL=https://traderboard-dev.traderverse.io/
       - INSTANCE_ID=instance156526
       - TOKEN=pxx7i93pzwgvdz6l
       - ERROR_CHAT_ID =120363424472771380@g.us
       - CHAT_ID =120363408117117262@g.us
       
       



    command: ["python3", "main.py"]