services:
  tradersboard_widgetloadtest:
    build: .
    container_name: tradersboard_widgetloadtest
    privileged: true
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DISPLAY=:99
      - ENVIRONMENT=production
      - EMAIL_USER=neksoftautomationdev@gmail.com
      - EMAIL_PASS=rxkqlgmswevrdzpi
      - BASE_URL=https://traderboard-dev.traderverse.io/
      - INSTANCE_ID=instance159663
      - TOKEN=pxx7i93pzwgvdz6l
      - ERROR_CHAT_ID=120363424472771380@g.us
      - CHAT_ID=120363408117117262@g.us
    command: ["python3", "main.py"]
